version: '3'

services:
  db:
    image: postgres
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine

  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db

volumes:
  pg_data: {}
